vich_uploader:
  db_driver: orm

  mappings:
    trick_image:
      uri_prefix: /uploads/tricks
      upload_destination: "%kernel.project_dir%/public/uploads/pins"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
      delete_on_update: true
      delete_on_remove: true
